version: "3.8"

services:
  # MongoDB database
  mongodb:
    image: mongo:7.0
    container_name: betfair-nlp-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: betfair_nlp
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Node.js API server
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: betfair-nlp-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./config:/app/config
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  # Apache proxy server
  apache-proxy:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: betfair-nlp-apache
    ports:
      - "80:80"
    depends_on:
      - api-server
    networks:
      - app-network
    restart: unless-stopped
    # Override the Apache config to point to the containerized API server
    command: >
      sh -c "
      sed -i 's/localhost:3000/api-server:3000/g' /usr/local/apache2/conf/extra/apache-proxy.conf &&
      httpd-foreground
      "

  # Mongo Express (optional, for database management)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: betfair-nlp-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
